inherit_from:
  - ".rubocop_todo.yml"
inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    - "config/rails.yml"
    - "config/rspec.yml"

AllCops:
  TargetRubyVersion: 2.4
  TargetRailsVersion: 5.1

# Rspecで使用するため
Style/MethodCalledOnDoEndBlock:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Exclude:
    - "bin/webpack"
    - "bin/webpack-dev-server"

Layout/AlignParameters:
  Exclude:
    - "bin/webpack"
    - "bin/webpack-dev-server"