# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dd452b99f38ec3759aaab96d22b697365dc36a7bf8251ca7d94e6b5ff22e28532cd885e9a2c64750127de57516169a61764a1ed6843db747e1ee80e21ef58c53

test:
  secret_key_base: 44390c537d6ec8cc86c9f155fa92a96f2e8a5411290fe3bf34a069b256426933fe5c50e1162cb50e5d0ac7c14cd6504dbac780648a4cfc3ff18df471344a55d1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
